# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='su_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='superuser',
            name=b'email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
