# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='yog',
            field=models.IntegerField(default=None),
        ),
    ]
