# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000)),
                ('rating', models.IntegerField(default=None)),
                ('ask', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
