# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('issuetype', models.CharField(default=None, max_length=100)),
                ('details', models.TextField(max_length=2000)),
                ('device', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
