# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name1',
        ),
    ]
