# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('internship_or_job', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='internship',
        ),
        migrations.AddField(
            model_name='experience',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumini.SuperUser'),
        ),
    ]
