# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0002_auto_20180325_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='superuser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
