# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0003_auto_20180325_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.Field()),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='email',
            new_name='object_name',
        ),
    ]
