# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0005_auto_20180328_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
